# Generated by Django 4.0.5 on 2022-06-05 16:12

from django.db import migrations


def add_initial_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.update_or_create(name="Trainer")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [migrations.RunPython(add_initial_groups)]
